name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Set NODE_OPTIONS for OpenSSL
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"
      run: echo "OpenSSL legacy provider configured"

    - name: Install frontend dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Test backend
      working-directory: ./backend
      run: npm test || echo "No backend tests defined, skipping"

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "/"
        api_location: "backend"
        output_location: "build" # Specify the correct build output location if different
        deployment_action: "upload"

    - name: Deploy backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: snakeGameAppService
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPPS_PUBLISH_PROFILE }}
        package: ./backend