name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean repository
      run: |
        rm -rf node_modules
        rm -rf backend/node_modules
        find . -name 'package-lock.json' -delete

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'

    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Test backend
      working-directory: ./backend
      run: npm test || echo "No backend tests defined, skipping"

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"
        api_location: "backend"
        output_location: "build"
        deployment_action: "upload"

    - name: Deploy backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: snakeGameAppService
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPPS_PUBLISH_PROFILE }}
        package: ./backend
